version: '3.8'

services:
  api-gateway:
    build: .
    container_name: api-gateway
    ports:
      - "8081:8081"
    env_file:
      - secrets.env
    depends_on:
      rr-auth:
        condition: service_healthy
      rr-store:
        condition: service_healthy
      rr-payments:
        condition: service_healthy
    networks:
      - shared_network

networks:
  shared_network:
    external: true
