apiVersion: v1
kind: Service
metadata:
  name: rr-gateway
  labels:
    app: rr-gateway
spec:
  selector:
    app: rr-gateway
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
